In [ ]:
import json
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_json('/content/orders.json')
data.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [ ]:
data.shape

(25000, 6)

In [ ]:
data.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

1.duplicate removal

In [ ]:
duplicate_rows = data[data.duplicated()]

print("Total Duplicate Rows:", duplicate_rows.shape[0])

duplicate_rows.head(10)

Total Duplicate Rows: 0

Empty DataFrame
Columns: [order_id, restaurant_name, order_date, order_value, discount_used, payment_method]
Index: []

Cleaning column: order_id

In [ ]:
data.order_id

0        8174c2af-07a4-4837-9068-1169d963e36e
1        0f9ddb57-4632-4a9f-9afe-1d2e41b94e32
2        099deda6-8c53-41cb-abf8-00126e6b2643
3        94a6ba27-d6ef-4d10-a026-ac0c0afa8505
4        216f3ec7-80a9-4d95-872f-715c37163b6d
                         ...
24995    74d3cd31-c1e0-4331-aad7-e1f48b4698ae
24996    14db2f6b-f722-44a2-ae55-fe42511e4bb2
24997    0fd85321-c1ce-4163-beca-c8ed2b472b8d
24998    6b96c699-2d63-4a3c-84f1-5d52ca4bf357
24999    af55e28b-27fc-49fc-bdb0-b297999dd152
Name: order_id, Length: 25000, dtype: object

In [ ]:
data.order_id.dtype

dtype('O')

In [ ]:
data.order_id.value_counts()

order_id
af55e28b-27fc-49fc-bdb0-b297999dd152    1
8174c2af-07a4-4837-9068-1169d963e36e    1
0f9ddb57-4632-4a9f-9afe-1d2e41b94e32    1
099deda6-8c53-41cb-abf8-00126e6b2643    1
94a6ba27-d6ef-4d10-a026-ac0c0afa8505    1
                                       ..
00a0c73e-b797-4322-afc4-6199d5f68ce9    1
11c7ea0f-cafa-4b63-a14e-7129fa934e95    1
28bcfd85-fd84-458c-851b-60311c625d01    1
25b2d40b-35b3-40f7-9cbe-37bf690db837    1
e44b23ce-6d29-4c09-9eac-9d4f24f56fd9    1
Name: count, Length: 25000, dtype: int64

In [ ]:
data.order_id.isnull().sum()

np.int64(0)

Cleaning column: restaurant_name

In [ ]:
data.restaurant_name

0                 TBC Sky Lounge
1        KC Das - Sweet Paradise
2              Hotel Kadamba Veg
3                  Cafe Srinidhi
4                         Pebble
                  ...
24995                   Carnatic
24996         Reddy's Restaurant
24997       BTM Bawarchi Biryani
24998                   Nite Out
24999                  Zee5 Loft
Name: restaurant_name, Length: 25000, dtype: object

In [ ]:
data.restaurant_name.dtype

dtype('O')

In [ ]:
data.restaurant_name.value_counts()

restaurant_name
Andhra Grills                              19
Cake Cafe                                  19
Hungry Lee                                 18
Shree Muthahalli Veg                       18
Orbis Restaurant                           18
                                           ..
24@43 - The Oterra                          1
Swathi Maharaja                             1
The Barn - Bar & Kitchen                    1
The Hub & The Bar - Hotel Ramada Encore     1
Kamat Bugle Rock                            1
Name: count, Length: 3159, dtype: int64

In [ ]:
data.restaurant_name.isnull().sum()

np.int64(0)

In [ ]:
data.restaurant_name = data.restaurant_name.str.lower()
data.restaurant_name = data.restaurant_name.str.strip()

Cleaning column: order_date

In [ ]:
data.order_date.dtype

dtype('O')

Changing datatype object to datetime

In [ ]:
data.order_date = pd.to_datetime(data.order_date)
data.order_date.dtype

dtype('<M8[ns]')

In [ ]:
data.order_date

0       2025-05-06
1       2026-01-08
2       2026-01-22
3       2025-11-10
4       2025-12-22
           ...
24995   2025-11-24
24996   2025-06-24
24997   2025-12-04
24998   2025-09-21
24999   2025-08-07
Name: order_date, Length: 25000, dtype: datetime64[ns]

In [ ]:
data.order_date.isnull().sum()

np.int64(0)

In [ ]:
data.order_date.value_counts()

order_date
2025-05-16    113
2026-01-08    112
2025-07-26    105
2025-11-05    105
2026-01-01    105
             ...
2025-09-16     65
2025-08-26     65
2026-02-23     64
2025-06-07     64
2025-11-22     55
Name: count, Length: 301, dtype: int64

In [ ]:
data.order_date

0       2025-05-06
1       2026-01-08
2       2026-01-22
3       2025-11-10
4       2025-12-22
           ...
24995   2025-11-24
24996   2025-06-24
24997   2025-12-04
24998   2025-09-21
24999   2025-08-07
Name: order_date, Length: 25000, dtype: datetime64[ns]

Cleaning column: order_value

In [ ]:
data.order_value

0         201.87
1        1392.27
2        1358.35
3         782.37
4        1551.09
          ...
24995    1254.91
24996     760.39
24997     707.99
24998     724.29
24999     905.00
Name: order_value, Length: 25000, dtype: float64

In [ ]:
data.order_value.dtype

dtype('float64')

In [ ]:
data.order_value.isnull().sum()

np.int64(0)

Cleaning column: discount_used

In [ ]:
data.discount_used

0         No
1         No
2        Yes
3         No
4        Yes
        ...
24995     No
24996     No
24997    Yes
24998    Yes
24999     No
Name: discount_used, Length: 25000, dtype: object

Changing Yes,No to True,False

In [ ]:
data.discount_used = data.discount_used.map({'Yes' : True, 'No' : False})

In [ ]:
data.discount_used

0        False
1        False
2         True
3        False
4         True
         ...
24995    False
24996    False
24997     True
24998     True
24999    False
Name: discount_used, Length: 25000, dtype: bool

In [ ]:
data.discount_used.dtype

dtype('bool')

In [ ]:
data.discount_used.isnull().sum()

np.int64(0)

In [ ]:
data.discount_used.value_counts()

discount_used
False    12509
True     12491
Name: count, dtype: int64

Cleaning column: payment_method

In [ ]:
data.payment_method

0        Card
1        Cash
2         UPI
3         UPI
4         UPI
         ...
24995     UPI
24996    Card
24997    Card
24998    Card
24999     UPI
Name: payment_method, Length: 25000, dtype: object

In [ ]:
data.payment_method.dtype

dtype('O')

In [ ]:
data.payment_method.isnull().sum()

np.int64(0)

In [ ]:
data.payment_method.value_counts()

payment_method
Cash    8384
Card    8364
UPI     8252
Name: count, dtype: int64

In [ ]:
data.payment_method = data.payment_method.str.lower()
data.payment_method = data.payment_method.str.strip()

In [ ]:
data.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,tbc sky lounge,2025-05-06,201.87,False,card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,kc das - sweet paradise,2026-01-08,1392.27,False,cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,hotel kadamba veg,2026-01-22,1358.35,True,upi
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,cafe srinidhi,2025-11-10,782.37,False,upi
4,216f3ec7-80a9-4d95-872f-715c37163b6d,pebble,2025-12-22,1551.09,True,upi

Storing the cleaned order_json file

In [ ]:
data.to_json('cleaned_order_data_version1.json', index=False)

print("Cleaned data successfully saved")

Cleaned data successfully saved

In [ ]:
df = pd.read_json('/content/cleaned_order_data_version1.json')
df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,tbc sky lounge,1746489600000,201.87,False,card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,kc das - sweet paradise,1767830400000,1392.27,False,cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,hotel kadamba veg,1769040000000,1358.35,True,upi
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,cafe srinidhi,1762732800000,782.37,False,upi
4,216f3ec7-80a9-4d95-872f-715c37163b6d,pebble,1766361600000,1551.09,True,upi